require("core.plugins")
require("core.options")
require("core.keymaps")

-- 插件
require("plugins.custom")
require("plugins.lualine")
require("plugins.nvim-tree")
require('plugins.impatient')
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
require("plugins.leap")
require("plugins.autosave")
require("plugins.lazygit")
