require("core.plugins")
require("core.options")
require("core.keymaps")

-- 插件

require("lsp")
require("plugins.cmp")
require("plugins.autocommands")
require("plugins.lualine")
require("plugins.nvim-tree")
require('plugins.impatient')
require("plugins.treesitter")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
require("plugins.leap")
require("plugins.autosave")
require("plugins.lazygit")
require("plugins.toggleterm")
require("plugins.indent-blankline")
require("plugins.vim-startify")
-- require("plugins.treesitter-textobjects")
require("plugins.hop")
require("plugins.fidget")
